version: '3'

services:

 node:
    image: node:16.7.0-buster
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
      - /app/node_modules

    command: ["nodejs", "dist/app.js"]
    ports:
      - ${NODE_EXPOSED_PORT:-0}:3000
